### ISSUE TITLE
travis-lint says that our .travis.yml file has unexpected globals

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-relier-client#60]
### Steps to reproduce:
1. ~~Install https://github.com/travis-ci/travis-lint~~ (or probably don't, it looks like that was deprecated a while ago).

    Go to http://lint.travis-ci.org/mozilla/fxa-relier-client

### Actual results:
> value for `env` section is empty, dropping
> in `env` section: value for `global` section is empty, dropping
> in `env.global`section: unexpected pair

#### [.travis.yml](https://github.com/mozilla/fxa-relier-client/blob/2dec9d43aa41a797a2c2bf341535f578685308df/.travis.yml#L3-L8):

```yml
env:
  global:
    # Sauce Labs are OK with this and it is currently necessary to expose this information for testing pull requests;
    # please get your own free key if you want to test yourself
    - SAUCE_USERNAME: fxa-client
    - SAUCE_ACCESS_KEY: 863203af-38fd-4f1d-9332-adc8f60f157b
```

It almost sounds like Travis is not using those configs...

Not sure if those two env variables should use a `=` instead of `:`, like so:
```yml
    - SAUCE_USERNAME=fxa-client
    - SAUCE_ACCESS_KEY=863203af-38fd-4f1d-9332-adc8f60f157b
```

When I change that, the Travis WebLint site says: _"Hooray, your .travis.yml seems to be solid!"_
